name: Run INAPORT Script Bi-weekly at 23:00

on:
  schedule:
    - cron: '0 23 1,15 * *'  # Every 2 weeks (1st and 15th of each month) at 23:00 UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours timeout

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run INAPORT script
      run: |
        python ina.py --kode all --tahun 2025

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: inaport-results
        path: |
          ina.csv